import { build } from 'esbuild';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';

await mkdir('dist/ui', { recursive: true });
await build({
  entryPoints: ['src/ui/app.ts'],
  bundle: true,
  format: 'iife',
  target: ['es2022'],
  outfile: 'dist/ui/app.js',
  sourcemap: true,
  legalComments: 'none',
});
await Promise.all([
  copyFile('src/ui/index.html', 'dist/ui/index.html'),
  copyFile('src/ui/styles.css', 'dist/ui/styles.css'),
]);
await mkdir('dist/assets/maps', { recursive: true });
await copyFile('src/assets/maps/garden-base-spring-v1.png', 'dist/assets/maps/garden-base-spring-v1.png');

const [html, css, appJs, mapBytes] = await Promise.all([
  readFile('dist/ui/index.html', 'utf8'),
  readFile('dist/ui/styles.css', 'utf8'),
  readFile('dist/ui/app.js', 'utf8'),
  readFile('src/assets/maps/garden-base-spring-v1.png'),
]);
const body = html.match(/<body>([\s\S]*?)<script src="\.\/app\.js"><\/script>[\s\S]*?<\/body>/i)?.[1];
if (!body) throw new Error('无法提取 UI body');
const mapDataUrl = `data:image/png;base64,${mapBytes.toString('base64')}`;
const mountBundle = `// generated by scripts/build-ui.mjs — local trusted binder only\n(() => {\n  'use strict';\n  const host = window.parent?.document ? window.parent : window;\n  const key = '__GENSOKYO_GARDEN_UI_020__';\n  host[key]?.destroy?.();\n  const doc = host.document;\n  const launcher = doc.createElement('button');\n  launcher.type = 'button';\n  launcher.textContent = '移动庭园';\n  launcher.id = 'gensokyo-garden-launcher';\n  Object.assign(launcher.style, {position:'fixed',right:'18px',bottom:'76px',zIndex:'2147483000',minHeight:'44px',padding:'9px 14px',borderRadius:'12px'});\n  const frame = doc.createElement('iframe');\n  frame.id = 'gensokyo-garden-frame';\n  frame.title = '幻想乡物语·移动庭园';\n  Object.assign(frame.style, {position:'fixed',inset:'32px 16px 64px',width:'calc(100% - 32px)',height:'calc(100% - 96px)',border:'0',borderRadius:'14px',zIndex:'2147482999',background:'#171a1e'});\n  doc.body.append(launcher, frame);\n  const child = frame.contentWindow;\n  const childDoc = frame.contentDocument;\n  childDoc.open();\n  childDoc.write('<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"></head><body></body></html>');\n  childDoc.close();\n  childDoc.documentElement.dataset.mapSrc = ${JSON.stringify(mapDataUrl)};\n  const style = childDoc.createElement('style');\n  style.textContent = ${JSON.stringify(css)};\n  childDoc.head.append(style);\n  childDoc.body.innerHTML = ${JSON.stringify(body)};\n  const source = window;\n  for (const name of ['waitGlobalInitialized','getChatMessages','createChatMessages','triggerSlash','getTavernVersion','getTavernHelperVersion','eventOn','getCurrentPersonaName','getPersona']) {\n    if (typeof source[name] === 'function') child[name] = source[name].bind(source);\n  }\n  for (const name of ['tavern_events','SillyTavern']) {\n    Object.defineProperty(child, name, { configurable:true, get:() => source[name] ?? host[name] });\n  }\n  Object.defineProperty(child, 'Mvu', { configurable:true, get:() => source.Mvu ?? host.Mvu });\n  Object.defineProperty(child, 'AutoCardUpdaterAPI', { configurable:true, get:() => host.AutoCardUpdaterAPI });\n  child.addEventListener('gensokyo-garden:show-native-chat', () => { frame.hidden = true; launcher.hidden = false; });\n  launcher.addEventListener('click', () => { frame.hidden = false; launcher.hidden = true; });\n  launcher.hidden = true;\n  const script = childDoc.createElement('script');\n  script.textContent = ${JSON.stringify(appJs)};\n  childDoc.body.append(script);\n  host[key] = { frame, launcher, destroy() { frame.remove(); launcher.remove(); delete host[key]; } };\n})();\n`;
const enhancedMountBundle = mountBundle
  .replace(
    "  doc.body.append(launcher, frame);",
    `  const close = doc.createElement('button');
  close.type = 'button';
  close.textContent = '收起庭园';
  close.id = 'gensokyo-garden-close';
  close.setAttribute('aria-label', '暂时隐藏移动庭园，返回原生聊天');
  Object.assign(close.style, {position:'fixed',right:'24px',top:'38px',zIndex:'2147483001',minHeight:'40px',padding:'7px 12px',borderRadius:'10px'});
  doc.body.append(launcher, frame, close);`,
  )
  .replace(
    "  child.addEventListener('gensokyo-garden:show-native-chat', () => { frame.hidden = true; launcher.hidden = false; });\n  launcher.addEventListener('click', () => { frame.hidden = false; launcher.hidden = true; });",
    `  const hideGarden = () => { frame.hidden = true; close.hidden = true; launcher.hidden = false; };
  const showGarden = () => { frame.hidden = false; close.hidden = false; launcher.hidden = true; };
  child.addEventListener('gensokyo-garden:show-native-chat', hideGarden);
  close.addEventListener('click', hideGarden);
  launcher.addEventListener('click', showGarden);`,
  )
  .replace(
    "  host[key] = { frame, launcher, destroy() { frame.remove(); launcher.remove(); delete host[key]; } };",
    "  host[key] = { frame, launcher, close, destroy() { frame.remove(); launcher.remove(); close.remove(); delete host[key]; } };",
  );
await mkdir('dist/runtime', { recursive: true });
await writeFile('dist/runtime/ui-mount.js', enhancedMountBundle, 'utf8');
