import { build } from 'esbuild';
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';

await mkdir('dist/ui', { recursive: true });
await build({
  entryPoints: ['src/ui/app.ts'],
  bundle: true,
  format: 'iife',
  target: ['es2022'],
  outfile: 'dist/ui/app.js',
  sourcemap: true,
  legalComments: 'none',
});
await Promise.all([
  copyFile('src/ui/index.html', 'dist/ui/index.html'),
  copyFile('src/ui/styles.css', 'dist/ui/styles.css'),
]);
await Promise.all([
  mkdir('dist/assets/maps', { recursive: true }),
  mkdir('dist/assets/characters/reimu', { recursive: true }),
  mkdir('dist/assets/characters/marisa', { recursive: true }),
  mkdir('dist/assets/world/house', { recursive: true }),
  mkdir('dist/assets/world/greenhouse', { recursive: true }),
]);
await Promise.all([
  copyFile('src/assets/maps/garden-base-spring-v1.png', 'dist/assets/maps/garden-base-spring-v1.png'),
  copyFile('src/assets/characters/reimu/reimu-turnaround-v1.png', 'dist/assets/characters/reimu/reimu-turnaround-v1.png'),
  copyFile('src/assets/characters/marisa/marisa-riding-turnaround-v3.png', 'dist/assets/characters/marisa/marisa-riding-turnaround-v3.png'),
  copyFile('src/assets/world/house/main-house-states-v1.png', 'dist/assets/world/house/main-house-states-v1.png'),
  copyFile('src/assets/world/greenhouse/magic-greenhouse-states-v1.png', 'dist/assets/world/greenhouse/magic-greenhouse-states-v1.png'),
]);

const [html, css, appJs, mapBytes, reimuSpriteBytes, marisaSpriteBytes, mainHouseBytes, greenhouseBytes, hostShellSource] = await Promise.all([
  readFile('dist/ui/index.html', 'utf8'),
  readFile('dist/ui/styles.css', 'utf8'),
  readFile('dist/ui/app.js', 'utf8'),
  readFile('src/assets/maps/garden-base-spring-v1.png'),
  readFile('src/assets/characters/reimu/reimu-turnaround-v1.png'),
  readFile('src/assets/characters/marisa/marisa-riding-turnaround-v3.png'),
  readFile('src/assets/world/house/main-house-states-v1.png'),
  readFile('src/assets/world/greenhouse/magic-greenhouse-states-v1.png'),
  readFile('src/runtime/ui-host-shell.js', 'utf8'),
]);
const body = html.match(/<body>([\s\S]*?)<script src="\.\/app\.js"><\/script>[\s\S]*?<\/body>/i)?.[1];
if (!body) throw new Error('无法提取 UI body');
const mapDataUrl = `data:image/png;base64,${mapBytes.toString('base64')}`;
const reimuSpriteDataUrl = `data:image/png;base64,${reimuSpriteBytes.toString('base64')}`;
const reimuPortraitDataUrl = reimuSpriteDataUrl;
const marisaSpriteDataUrl = `data:image/png;base64,${marisaSpriteBytes.toString('base64')}`;
const marisaPortraitDataUrl = marisaSpriteDataUrl;
const mainHouseDataUrl = `data:image/png;base64,${mainHouseBytes.toString('base64')}`;
const greenhouseDataUrl = `data:image/png;base64,${greenhouseBytes.toString('base64')}`;
const embedded = {
  body,
  css,
  appJs,
  mapDataUrl,
  reimuSpriteDataUrl,
  reimuPortraitDataUrl,
  marisaSpriteDataUrl,
  marisaPortraitDataUrl,
  mainHouseDataUrl,
  greenhouseDataUrl,
};
const enhancedMountBundle = [
  '// generated by scripts/build-ui.mjs — local trusted binder only',
  `const embedded = ${JSON.stringify(embedded)};`,
  hostShellSource,
].join('\n');
await mkdir('dist/runtime', { recursive: true });
await writeFile('dist/runtime/ui-mount.js', enhancedMountBundle, 'utf8');
